baseurl = "https://writer-life-committee.github.io/web-test/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "作家の手帖"
theme = "universal"
#themesDir = "themes/hugo-universal-theme"
languageCode = "ja"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "ja"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[markup.goldmark.renderer]
unsafe = true 

[menu]


# Main menu
[[menu.main]]
    name       = "企画について"
    identifier = "menu.project"
    url        = "/img/template-easy-customize.png"
    weight     = 1
[[menu.main]]
    name       = "「作家の手帖」の特徴"
    url        = ""
    weight     = 1
    parent     = "menu.project"
[[menu.main]]
    name       = "原稿料とは"
    url        = ""
    weight     = 2
    parent     = "menu.project"
[[menu.main]]
    name       = "スケジュール"
    url        = ""
    weight     = 3
    parent     = "menu.project"

[[menu.main]]
    name       = "目次"
    identifier = "menu.portfolio"
    weight     = 2

[[menu.main]]
    name       = "準備1号"
    identifier = "section.portfolio"
    weight     = 1
    parent     = "menu.portfolio"
    post       = 1

[[menu.main]]
    name       = "【1.企画趣旨】笠井康平"
    url        = "/blog/2021/08/09/kasai"
    weight     = 1
    parent     = "section.portfolio"
    post       = 2

[[menu.main]]
    name       = "【4.原稿料】うっかり"
    url        = "/blog/2021/08/14/ukkari/"
    weight     = 1
    parent     = "section.portfolio"
    post       = 3

[[menu.main]]
    name       = "【6.契約・交渉】ひらりさ"
    url        = "/blog/2021/08/13/hirarisa/"
    weight     = 1
    parent     = "section.portfolio"
    post       = 4

[[menu.main]]
    name       = "【7.選考】伏見瞬"
    url        = "/blog/2021/08/15/fushimi/"
    weight     = 1
    parent     = "section.portfolio"
    post       = 5
    
[[menu.main]]
    name       = "【8.執筆】大滝瓶太"
    url        = ""
    weight     = 1
    parent     = "section.portfolio"
    post       = 6

[[menu.main]]
    name       = "【15.流通・販売】関口竜平"
    url        = "/blog/2021/08/11/sekiguchi/"
    weight     = 1
    parent     = "section.portfolio"
    post       = 6

[[menu.main]]
    name       = "【16.パブリシティ】小澤みゆき"
    url        = "/blog/2021/08/12/ozawa"
    weight     = 1
    parent     = "section.portfolio"
    post       = 7
[[menu.main]]
    name       = "【18.財務・会計】poroLogue"
    url        = "/blog/2021/08/15/porologue/"
    weight     = 1
    parent     = "section.portfolio"
    post       = 8

[[menu.main]]
    name       = "準備2号"
    identifier = "section.about"
    url        = ""
    weight     = 1
    parent     = "menu.portfolio"
    post       = 2

[[menu.main]]
    name       = "To Bo Continued..."
    url        = ""
    weight     = 1
    parent     = "section.about"

[[menu.main]]
    name       = "規約類・事務書類"
    identifier = "menu.papers"
    weight     = 3

[[menu.main]]
    name       = "リーガル"
    identifier = "section.regal"
    weight     = 1
    parent     = "menu.papers"
    post       = 1

[[menu.main]]
    name       = "団体規約"
    url        = ""
    weight     = 1
    parent     = "section.regal"
    post       = 1
    
[[menu.main]]
    name       = "業務委託共通規約（仕様書項目、個人情報保護特約を含む）"
    url        = ""
    weight     = 1
    parent     = "section.regal"
    post       = 2

[[menu.main]]
    name       = "業務委託仕様書（執筆者向けひな型・記入例）"
    url        = ""
    weight     = 1
    parent     = "section.regal"
    post       = 3

[[menu.main]]
    name       = "「作家の手帖」発注書（テンプレート）"
    url        = ""
    weight     = 1
    parent     = "section.regal"
    post       = 4

[[menu.main]]
    name       = "「作家の手帖」参加規約"
    url        = ""
    weight     = 1
    parent     = "section.regal"
    post       = 5

[[menu.main]]
    name       = "「作家の手帖」プライバシーポリシー"
    url        = ""
    weight     = 1
    parent     = "section.regal"
    post       = 6

[[menu.main]]
    name       = "執筆依頼"
    identifier = "section.request"
    url        = ""
    weight     = 2
    parent     = "menu.papers"
    post       = 2

[[menu.main]]
    name       = "共通執筆依頼書"
    url        = ""
    weight     = 1
    parent     = "section.request"
    post       = 1
    
[[menu.main]]
    name       = "執筆応募フォーム"
    url        = ""
    weight     = 1
    parent     = "section.request"
    post       = 2
[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 4

[[menu.main]]
    name       = "チケット購入"
    identifier = "ticket"
    url        = "https://authors-note.stores.jp/?_ga=2.19211121.852579254.1630027136-147843420.1616418251"
    weight     = 7


[params]
    viewMorePostLink = "/blog/"
    author = "文筆生活向上委員会"
    defaultKeywords = ["原稿料", "書籍", "編集"]
    mainSections = ["blog"]
    defaultDescription = "広く原稿料について考えるウェブ同人誌「作家の手帖」のサイトです。"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    #default_sharing_image = "img/sharing-default.png"
	default_sharing_image = "img/author-note-banner.png"
	
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>文筆生活向上委員会（編集長：笠井康平・小澤みゆき）</p>"
    copyright = "Copyright (c) 2021 , Writer Life Committee; All rights reserved."

    # Format dates with Go's time formatting
    date_format = "August 28, 2021"

    disabled_logo = true
    logo_text = "作家の手帖"

    logo = "img/logo.png"
    logo_small = "img/logo.png"
    address = """<a href="https://authors-note.stores.jp/items/6078e843d5e9c9671858a8ec/" class="button">チケットを購入する</a>"""

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = false
    search = false

[params.carouselCustomers]
    items = 2
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 1 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "準備2号"
    subtitle = "今秋から製作予定の記事を発表しています。"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "参加方法"
    subtitle = "STORESで参加チケットを販売しています。購入すると、次の特典を受け取れます。<ul><li>完成稿（PDF/epub）の入手</li><li>制作過程（草稿/編集稿/初稿/校正稿）の赤入れやコメントの閲覧</li><li>オンライン勉強会のアーカイヴ動画視聴</li><li>参加者コミュニティ（Discord）への参加</li><li>招待状（紙）</li></ul>このささやかな取り組みを支援していただける方は、ぜひ参加チケットをお買い求めください。"
    link_url = "https://authors-note.stores.jp/?_ga=2.19211121.852579254.1630027136-147843420.1616418251"
    link_text = "チケットを購入する"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "ご支援のお願い"
    subtitle = "ここに寄付ください的な文章が入ります"

[params.recent_posts]
    enable = true
    title = "執筆原稿"
    subtitle = "準備1号で執筆いただいたテキストの「初稿」を公開しています。「完成稿」はチケット購入者のみ入手可能です。"
    hide_summary = true

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
